### ISSUE TITLE
C# SDK / Unity plugin 

### ISSUE THREAD

**Issue by yosun** [amadeus4dev/hackathon-starter#3]
?

**Comment by anthonyroux** [comment]
We are working on a C# SDK, unfortunately it takes longer than expected due to the limit number of resources we have. We will be more than happy to open what we have for contributions!

**Comment by yosun** [comment]
Sure, please do

**Comment by anthonyroux** [comment]
I just put the project in public, you can find it [here](https://github.com/amadeus4dev/amadeus-dotnet-wip/blob/master/README.md).

Please take a look at our [specification](https://github.com/amadeus4dev/amadeus-sdk-specification) that we follow for all our SDKs.

Feel free to contribute, let us know if you need anything!
